### ISSUE TITLE
Left click on the icon throws an error in Windows

### ISSUE THREAD

**Issue by kmchmk** [kmchmk/SLT-Data-Usage#11]
> An error occurred when calling message handler
> Traceback (most recent call last):
>   File "C:\Users\kmchmk\AppData\Local\Programs\Python\Python39\lib\site-packages\pystray\_win32.py", line 398, in _dispatcher
>     return int(icon._message_handlers.get(
>   File "C:\Users\kmchmk\AppData\Local\Programs\Python\Python39\lib\site-packages\pystray\_win32.py", line 187, in _on_notify
>     self()
>   File "C:\Users\kmchmk\AppData\Local\Programs\Python\Python39\lib\site-packages\pystray\_base.py", line 88, in __call__
>     self._menu(self)
> TypeError: 'tuple' object is not callable

**Comment by kmchmk** [comment]
Reason found: https://github.com/moses-palmer/pystray/issues/38
